// Code generated by wayland-scanner. DO NOT EDIT.
// Protocol: wlvision_fixture
// Source: protocol_fixture.xml

package protocoltest

import (
	"github.com/bnema/wlturbo/wl"
)

// FIXTURE_STATE_IDLE is the fixture_state idle value.
const FIXTURE_STATE_IDLE int32 = 0

// FIXTURE_STATE_BUSY is the fixture_state busy value.
const FIXTURE_STATE_BUSY int32 = 1

// FixtureManagerInterface is the protocol interface name.
const FixtureManagerInterface = "zwlr_fixture_manager_v1"

// FixtureManager is the generated binding for zwlr_fixture_manager_v1 version 2.
type FixtureManager struct {
	wl.BaseProxy
}

// NewFixtureManager returns an unbound FixtureManager.
func NewFixtureManager(ctx *wl.Context) *FixtureManager {
	obj := &FixtureManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// create a fixture object
func (o *FixtureManager) CreateThing(seat *wl.Seat) (*FixtureThing, error) {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	child := &FixtureThing{}
	child.SetContext(o.Context())
	child.SetID(o.Context().AllocateID())
	o.Context().Register(child)
	if err := o.Context().SendRequest(o, 0, arg0, child); err != nil {
		o.Context().Unregister(child)
		return nil, err
	}
	return child, nil
}
func (o *FixtureManager) SetRatio(ratio wl.Fixed) error {
	if err := o.Context().SendRequest(o, 1, ratio); err != nil {
		return err
	}
	return nil
}
func (o *FixtureManager) SetLabel(label string) error {
	if err := o.Context().SendRequest(o, 2, label); err != nil {
		return err
	}
	return nil
}
func (o *FixtureManager) SetRegion(region *wl.Region) error {
	var arg0 wl.Object
	if region != nil {
		arg0 = region
	}
	if err := o.Context().SendRequest(o, 3, arg0); err != nil {
		return err
	}
	return nil
}

// reference an interface without a typed wrapper
func (o *FixtureManager) SetBuffer(buffer *wl.BaseProxy) error {
	var arg0 wl.Object
	if buffer != nil {
		arg0 = buffer
	}
	if err := o.Context().SendRequest(o, 4, arg0); err != nil {
		return err
	}
	return nil
}
func (o *FixtureManager) SetOptionalOutput(output *wl.Output) error {
	var arg0 wl.Object
	if output != nil {
		arg0 = output
	}
	if err := o.Context().SendRequest(o, 5, arg0); err != nil {
		return err
	}
	return nil
}
func (o *FixtureManager) AttachRaw(data []byte) error {
	if err := o.Context().SendRequest(o, 6, data); err != nil {
		return err
	}
	return nil
}
func (o *FixtureManager) PassFd(fd int) error {
	if err := o.Context().SendRequestWithFDs(o, 7, []int{fd}, uintptr(fd)); err != nil {
		return err
	}
	return nil
}

// destroy the manager
func (o *FixtureManager) Destroy() error {
	if err := o.Context().SendRequest(o, 8); err != nil {
		return err
	}
	o.Context().Unregister(o)
	return nil
}

// Dispatch decodes one event on zwlr_fixture_manager_v1 and calls the registered handlers.
func (o *FixtureManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// FixtureThingInterface is the protocol interface name.
const FixtureThingInterface = "zwlr_fixture_thing_v1"

// FixtureThing is the generated binding for zwlr_fixture_thing_v1 version 1.
type FixtureThing struct {
	wl.BaseProxy
	onReady        []func(serial uint32)
	onLabelChanged []func(label string)
	onGeometry     []func(x int32, y int32, width uint32, height uint32)
	onMode         []func(modeObject *FixtureMode)
	onPeer         []func(surfaceID uint32)
	onScaled       []func(scale wl.Fixed)
	onBlob         []func(data []byte)
}

// NewFixtureThing returns an unbound FixtureThing.
func NewFixtureThing(ctx *wl.Context) *FixtureThing {
	obj := &FixtureThing{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}
func (o *FixtureThing) SetScale(scale wl.Fixed) error {
	if err := o.Context().SendRequest(o, 0, scale); err != nil {
		return err
	}
	return nil
}
func (o *FixtureThing) Destroy() error {
	if err := o.Context().SendRequest(o, 1); err != nil {
		return err
	}
	o.Context().Unregister(o)
	return nil
}

// OnReady registers a handler for the ready event.
func (o *FixtureThing) OnReady(handler func(serial uint32)) {
	o.onReady = append(o.onReady, handler)
}

// OnLabelChanged registers a handler for the label_changed event.
func (o *FixtureThing) OnLabelChanged(handler func(label string)) {
	o.onLabelChanged = append(o.onLabelChanged, handler)
}

// OnGeometry registers a handler for the geometry event.
func (o *FixtureThing) OnGeometry(handler func(x int32, y int32, width uint32, height uint32)) {
	o.onGeometry = append(o.onGeometry, handler)
}

// OnMode registers a handler for the mode event.
func (o *FixtureThing) OnMode(handler func(modeObject *FixtureMode)) {
	o.onMode = append(o.onMode, handler)
}

// OnPeer registers a handler for the peer event.
func (o *FixtureThing) OnPeer(handler func(surfaceID uint32)) {
	o.onPeer = append(o.onPeer, handler)
}

// OnScaled registers a handler for the scaled event.
func (o *FixtureThing) OnScaled(handler func(scale wl.Fixed)) {
	o.onScaled = append(o.onScaled, handler)
}

// OnBlob registers a handler for the blob event.
func (o *FixtureThing) OnBlob(handler func(data []byte)) {
	o.onBlob = append(o.onBlob, handler)
}

// Dispatch decodes one event on zwlr_fixture_thing_v1 and calls the registered handlers.
func (o *FixtureThing) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // ready
		serial := event.Uint32()
		for _, handler := range o.onReady {
			handler(serial)
		}
	case 1: // label_changed
		label := event.String()
		for _, handler := range o.onLabelChanged {
			handler(label)
		}
	case 2: // geometry
		x := event.Int32()
		y := event.Int32()
		width := event.Uint32()
		height := event.Uint32()
		for _, handler := range o.onGeometry {
			handler(x, y, width, height)
		}
	case 3: // mode
		modeID := event.Uint32()
		modeObject := &FixtureMode{}
		modeObject.SetContext(o.Context())
		modeObject.SetID(modeID)
		o.Context().Register(modeObject)
		for _, handler := range o.onMode {
			handler(modeObject)
		}
	case 4: // peer
		surfaceID := event.Uint32()
		for _, handler := range o.onPeer {
			handler(surfaceID)
		}
	case 5: // scaled
		scale := event.Fixed()
		for _, handler := range o.onScaled {
			handler(scale)
		}
	case 6: // blob
		data := event.Array()
		for _, handler := range o.onBlob {
			handler(data)
		}
	default:
	}
}

// FixtureModeInterface is the protocol interface name.
const FixtureModeInterface = "zwlr_fixture_mode_v1"

// FixtureMode is the generated binding for zwlr_fixture_mode_v1 version 1.
type FixtureMode struct {
	wl.BaseProxy
}

// NewFixtureMode returns an unbound FixtureMode.
func NewFixtureMode(ctx *wl.Context) *FixtureMode {
	obj := &FixtureMode{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}
func (o *FixtureMode) Destroy() error {
	if err := o.Context().SendRequest(o, 0); err != nil {
		return err
	}
	o.Context().Unregister(o)
	return nil
}

// Dispatch decodes one event on zwlr_fixture_mode_v1 and calls the registered handlers.
func (o *FixtureMode) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
