package scanner

// protocolTemplate is the template for generating WLTurbo-backed Go bindings.
//
// Generated objects embed wl.BaseProxy, allocate and register child objects
// through the wl.Context, send requests through that context, and dispatch
// typed events to registered handlers. Nothing in the generated code opens a
// socket or frames messages itself: that is the transport's job.
const protocolTemplate = `// Code generated by wayland-scanner. DO NOT EDIT.
// Protocol: {{.Protocol}}
// Source: {{.Source}}

package {{.Package}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

{{range .Constants}}
// {{.Name}} is the {{.Enum}} {{.Entry}} value.
const {{.Name}} {{.Type}} = {{.Value}}
{{- end}}
{{range .Interfaces}}
{{- $iface := .}}

// {{$iface.GoName}}Interface is the protocol interface name.
const {{$iface.GoName}}Interface = "{{$iface.Name}}"

// {{$iface.GoName}} is the generated binding for {{$iface.Name}} version {{$iface.Version}}.
type {{$iface.GoName}} struct {
	wl.BaseProxy
{{- range $iface.Events}}
	{{.HandlerField}} []func({{.HandlerParams}})
{{- end}}
}

// New{{$iface.GoName}} returns an unbound {{$iface.GoName}}.
func New{{$iface.GoName}}(ctx *wl.Context) *{{$iface.GoName}} {
	obj := &{{$iface.GoName}}{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}
{{- range $iface.Requests}}

{{- if .Doc}}
// {{.Doc}}
{{- end}}
func (o *{{$iface.GoName}}) {{.GoName}}({{.Params}}) {{.Results}} {
{{- range .ArgPreparations}}
	{{.}}
{{- end}}
{{- if .CreatesChild}}
	{{.ChildVar}} := &{{.ChildType}}{}
	{{.ChildVar}}.SetContext(o.Context())
	{{.ChildVar}}.SetID(o.Context().AllocateID())
	o.Context().Register({{.ChildVar}})
{{- end}}
	if err := o.Context().{{.SendCall}}; err != nil {
{{- if .CreatesChild}}
		o.Context().Unregister({{.ChildVar}})
{{- end}}
		return {{.ErrorReturn}}
	}
{{- if .Destructor}}
	o.Context().Unregister(o)
{{- end}}
{{- if .CreatesChild}}
	return {{.ChildVar}}, nil
{{- else}}
	return nil
{{- end}}
}
{{- end}}
{{- range $iface.Events}}

// On{{.GoName}} registers a handler for the {{.Name}} event.
func (o *{{$iface.GoName}}) On{{.GoName}}(handler func({{.HandlerParams}})) {
	o.{{.HandlerField}} = append(o.{{.HandlerField}}, handler)
}
{{- end}}

// Dispatch decodes one event on {{$iface.Name}} and calls the registered handlers.
func (o *{{$iface.GoName}}) Dispatch(event *wl.Event) {
	switch event.Opcode {
{{- range $iface.Events}}
	case {{.Opcode}}: // {{.Name}}
{{- range .DecodeLines}}
		{{.}}
{{- end}}
		for _, handler := range o.{{.HandlerField}} {
			handler({{.HandlerArgs}})
		}
{{- end}}
	default:
	}
}
{{end}}
`
