// Package protocols contains device-specific Wayland bindings generated by WLTurbo.
package protocols

//go:generate go run github.com/bnema/wlturbo/cmd/wlturbo-scanner -p protocols -o virtual_keyboard_generated.go -import wl_seat=github.com/bnema/wlturbo/protocol/core ../../protocol/virtual-keyboard-unstable-v1.xml
//go:generate go run github.com/bnema/wlturbo/cmd/wlturbo-scanner -p protocols -o virtual_pointer_generated.go -import wl_seat=github.com/bnema/wlturbo/protocol/core -import wl_output=github.com/bnema/wlturbo/protocol/core ../../protocol/wlr-virtual-pointer-unstable-v1.xml
//go:generate go run github.com/bnema/wlturbo/cmd/wlturbo-scanner -p protocols -o pointer_constraints_generated.go -import wl_surface=github.com/bnema/wlturbo/protocol/core -import wl_pointer=github.com/bnema/wlturbo/protocol/core -import wl_region=github.com/bnema/wlturbo/protocol/core ../../protocol/pointer-constraints-unstable-v1.xml
//go:generate go run github.com/bnema/wlturbo/cmd/wlturbo-scanner -p protocols -o output_management_generated.go ../../protocol/wlr-output-management-unstable-v1.xml
//go:generate go run github.com/bnema/wlturbo/cmd/wlturbo-scanner -p protocols -o keyboard_shortcuts_inhibitor_generated.go -import wl_surface=github.com/bnema/wlturbo/protocol/core -import wl_seat=github.com/bnema/wlturbo/protocol/core ../../protocol/keyboard-shortcuts-inhibit-unstable-v1.xml
