// Code generated by wayland-scanner. DO NOT EDIT.
// Protocol: keyboard_shortcuts_inhibit_unstable_v1
// Source: keyboard-shortcuts-inhibit-unstable-v1.xml

package protocols

import (
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ALREADY_INHIBITED is the error already_inhibited value.
const ERROR_ALREADY_INHIBITED int32 = 0

// KeyboardShortcutsInhibitManagerInterface is the protocol interface name.
const KeyboardShortcutsInhibitManagerInterface = "zwp_keyboard_shortcuts_inhibit_manager_v1"

// KeyboardShortcutsInhibitManager is the generated binding for zwp_keyboard_shortcuts_inhibit_manager_v1 version 1.
type KeyboardShortcutsInhibitManager struct {
	wl.BaseProxy
}

// NewKeyboardShortcutsInhibitManager returns an unbound KeyboardShortcutsInhibitManager.
func NewKeyboardShortcutsInhibitManager(ctx *wl.Context) *KeyboardShortcutsInhibitManager {
	obj := &KeyboardShortcutsInhibitManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the keyboard shortcuts inhibitor manager.
func (o *KeyboardShortcutsInhibitManager) Destroy() error {
	if err := o.Context().SendRequest(o, 0); err != nil {
		return err
	}
	o.Context().Unregister(o)
	return nil
}

// Create a new keyboard shortcuts inhibitor object associated with the given surface for the given seat. If shortcuts are already inhibited for the specified seat and surface, a protocol error "already_inhibited" is raised by the compositor.
func (o *KeyboardShortcutsInhibitManager) InhibitShortcuts(surface *wl.Surface, seat *wl.Seat) (*KeyboardShortcutsInhibitor, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	var arg2 wl.Object
	if seat != nil {
		arg2 = seat
	}
	child := &KeyboardShortcutsInhibitor{}
	child.SetContext(o.Context())
	child.SetID(o.Context().AllocateID())
	o.Context().Register(child)
	if err := o.Context().SendRequest(o, 1, child, arg1, arg2); err != nil {
		o.Context().Unregister(child)
		return nil, err
	}
	return child, nil
}

// Dispatch decodes one event on zwp_keyboard_shortcuts_inhibit_manager_v1 and calls the registered handlers.
func (o *KeyboardShortcutsInhibitManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// KeyboardShortcutsInhibitorInterface is the protocol interface name.
const KeyboardShortcutsInhibitorInterface = "zwp_keyboard_shortcuts_inhibitor_v1"

// KeyboardShortcutsInhibitor is the generated binding for zwp_keyboard_shortcuts_inhibitor_v1 version 1.
type KeyboardShortcutsInhibitor struct {
	wl.BaseProxy
	onActive   []func()
	onInactive []func()
}

// NewKeyboardShortcutsInhibitor returns an unbound KeyboardShortcutsInhibitor.
func NewKeyboardShortcutsInhibitor(ctx *wl.Context) *KeyboardShortcutsInhibitor {
	obj := &KeyboardShortcutsInhibitor{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Remove the keyboard shortcuts inhibitor from the associated wl_surface.
func (o *KeyboardShortcutsInhibitor) Destroy() error {
	if err := o.Context().SendRequest(o, 0); err != nil {
		return err
	}
	o.Context().Unregister(o)
	return nil
}

// OnActive registers a handler for the active event.
func (o *KeyboardShortcutsInhibitor) OnActive(handler func()) {
	o.onActive = append(o.onActive, handler)
}

// OnInactive registers a handler for the inactive event.
func (o *KeyboardShortcutsInhibitor) OnInactive(handler func()) {
	o.onInactive = append(o.onInactive, handler)
}

// Dispatch decodes one event on zwp_keyboard_shortcuts_inhibitor_v1 and calls the registered handlers.
func (o *KeyboardShortcutsInhibitor) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // active
		for _, handler := range o.onActive {
			handler()
		}
	case 1: // inactive
		for _, handler := range o.onInactive {
			handler()
		}
	default:
	}
}
