// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: virtual_keyboard_unstable_v1
// Source: virtual-keyboard-unstable-v1.xml

package protocols

import (
	cross_wl_seat "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_NO_KEYMAP is the error no_keymap value.
const ERROR_NO_KEYMAP = 0

// ERROR_UNAUTHORIZED is the error unauthorized value.
const ERROR_UNAUTHORIZED = 0

// VirtualKeyboardInterface is the protocol interface name.
const VirtualKeyboardInterface = "zwp_virtual_keyboard_v1"

// VirtualKeyboard is the generated binding for zwp_virtual_keyboard_v1 version 1.
type VirtualKeyboard struct {
	wl.BaseProxy
}

// NewVirtualKeyboard returns an unbound VirtualKeyboard.
func NewVirtualKeyboard(ctx *wl.Context) *VirtualKeyboard {
	obj := &VirtualKeyboard{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Provide a file descriptor to the compositor which can be memory-mapped to provide a keyboard mapping description. Format carries a value from the keymap_format enumeration.
func (o *VirtualKeyboard) Keymap(format uint32, fd int, size uint32) error {
	if err := o.Context().CheckProxy(o); err != nil {
		return err
	}
	if err := o.Context().SendRequestWithFDs(o, 0, []int{fd}, format, uintptr(fd), size); err != nil {
		return err
	}
	_ = wl.CloseSentFD(fd)
	return nil
}

// A key was pressed or released. The time argument is a timestamp with millisecond granularity, with an undefined base. All requests regarding a single object must share the same clock. Keymap must be set before issuing this request. State carries a value from the key_state enumeration.
func (o *VirtualKeyboard) Key(time uint32, key uint32, state uint32) error {
	if err := o.Context().CheckProxy(o); err != nil {
		return err
	}
	if err := o.Context().SendRequest(o, 1, time, key, state); err != nil {
		return err
	}
	return nil
}

// Notifies the compositor that the modifier and/or group state has changed, and it should update state. The client should use wl_keyboard.modifiers event to synchronize its internal state with seat state. Keymap must be set before issuing this request.
func (o *VirtualKeyboard) Modifiers(modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32) error {
	if err := o.Context().CheckProxy(o); err != nil {
		return err
	}
	if err := o.Context().SendRequest(o, 2, modsDepressed, modsLatched, modsLocked, group); err != nil {
		return err
	}
	return nil
}

// destroy the virtual keyboard keyboard object
func (o *VirtualKeyboard) Destroy() error {
	if err := o.Context().CheckProxy(o); err != nil {
		return err
	}
	if err := o.Context().SendDestructor(o, 3); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *VirtualKeyboard) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_virtual_keyboard_v1 and calls the registered handlers.
func (o *VirtualKeyboard) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// VirtualKeyboardManagerInterface is the protocol interface name.
const VirtualKeyboardManagerInterface = "zwp_virtual_keyboard_manager_v1"

// VirtualKeyboardManager is the generated binding for zwp_virtual_keyboard_manager_v1 version 1.
type VirtualKeyboardManager struct {
	wl.BaseProxy
}

// NewVirtualKeyboardManager returns an unbound VirtualKeyboardManager.
func NewVirtualKeyboardManager(ctx *wl.Context) *VirtualKeyboardManager {
	obj := &VirtualKeyboardManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Creates a new virtual keyboard associated to a seat. If the compositor enables a keyboard to perform arbitrary actions, it should present an error when an untrusted client requests a new keyboard.
func (o *VirtualKeyboardManager) CreateVirtualKeyboard(seat *cross_wl_seat.Seat) (*VirtualKeyboard, error) {
	if err := o.Context().CheckProxy(o); err != nil {
		return nil, err
	}
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	child := &VirtualKeyboard{}
	child.SetContext(o.Context())
	child.SetID(o.Context().AllocateID())
	o.Context().Register(child)
	if err := o.Context().SendRequest(o, 0, arg0, child); err != nil {
		o.Context().Unregister(child)
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *VirtualKeyboardManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_virtual_keyboard_manager_v1 and calls the registered handlers.
func (o *VirtualKeyboardManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
